services:
  - type: web
    name: hopspot-backend
    env: node
    plan: free
    rootDir: Busapp/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
